name: Test, build and publish

on:
  push:
    branches:
      - master

env:
  CI: true
jobs:
  test-build-publish:
    if: "!contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[fix]') || contains(github.event.head_commit.message, '[feat]') || contains(github.event.head_commit.message, '[breaking]')"
    name: Test and build
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org
          node-version: 14
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:coverage
      - name: Build
        run: npm run build

      - name: Setup git auth for lerna
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://github-actions[bot]:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git

      - name: Update changed packages with PATCH
        if: "contains(github.event.head_commit.message, '[fix]')"
        run: npm run lerna version patch --include-merged-tags --yes
      - name: Update changed packages with MINOR
        if: "contains(github.event.head_commit.message, '[feat]')"
        run: npm run lerna version minor --include-merged-tags --yes
      - name: Update changed packages with MAJOR
        if: "contains(github.event.head_commit.message, '[breaking]')"
        run: npm run lerna version major --include-merged-tags --yes

      - name: Publish to NPM registry
        run: npm run lerna publish --no-verify-access from-package --yes

      - name: Create a .npmrc file for the github package repository
        uses: FerLuisxd/create-npmrc@3
        with:
          org_name: navikt
        env:
          AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish to GPR
        run: |
          npm run lerna publish --registry https://npm.pkg.github.com from-package --yes